name: Publish Packages

on:
  push:
    branches:
      - "releases-slash/*"
      - "releases-client/*"
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  publish-client:
    if: github.repository_owner == 'AxaFrance' && !startsWith(github.ref, 'refs/heads/releases-slash/')
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.fullSemVer }}
      isStableRelease: ${{ steps.gitversion.outputs.preReleaseTag == '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: ./.github/action/setup-node

      - name: Determine Version
        id: gitversion
        uses: ./.github/action/git-version
        with:
          configFilePath: "GitVersion-client.yml"

      - name: Build packages
        run: |
          npm run build:apollo
          npm run build:look-and-feel

      - name: Npm version
        run:
          npm version "${{ steps.gitversion.outputs.fullSemVer }}" -w
          client/apollo/css -w client/apollo/react -w
          client/look-and-feel/css -w client/look-and-feel/react

      - name: Update package.json
        run: |
          node scripts/pre-publish.js client

      - name: Publish packages
        run: |
          if [ "${{ steps.gitversion.outputs.preReleaseTag }}" = "" ]; then
            npm publish -w client/apollo/css -w client/apollo/react -w client/look-and-feel/css -w client/look-and-feel/react --access public --tag latest;
          else
            npm publish -w client/apollo/css -w client/apollo/react -w client/look-and-feel/css -w client/look-and-feel/react --access public --tag next;
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create artifact folders
        uses: ./.github/action/create-storybook-artifact
        with:
          artifact-name: client-storybooks
          folders: "apollo/react,look-and-feel/react"

  publish-slash:
    if: github.repository_owner == 'AxaFrance' && !startsWith(github.ref, 'refs/heads/releases-client/')
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.fullSemVer }}
      isStableRelease: ${{ steps.gitversion.outputs.preReleaseTag == '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: ./.github/action/setup-node

      - name: Determine Version
        id: gitversion
        uses: ./.github/action/git-version
        with:
          configFilePath: "GitVersion-slash.yml"

      - name: Build packages
        run: npm run build:slash

      - name: Npm version
        run:
          npm version "${{ steps.gitversion.outputs.fullSemVer }}" -w slash/css
          -w slash/react

      - name: Update package.json
        run: node scripts/pre-publish.js slash

      - name: Publish packages
        run: |
          if [ "${{ steps.gitversion.outputs.preReleaseTag }}" = "" ]; then
            npm publish -w slash/css -w slash/react --access public --tag latest;
          else
            npm publish -w slash/css -w slash/react --access public --tag next;
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create artifact folders
        uses: ./.github/action/create-storybook-artifact
        with:
          artifact-name: slash-storybooks
          folders: "slash/react"

  deploy-storybooks:
    needs:
      - publish-client
      - publish-slash
    runs-on: ubuntu-latest
    name: Deploy new version of storybook to gh-pages
    strategy:
      matrix:
        storybook:
          - name: apollo react
            destination_dir: apollo/react
            artifact-name: client-storybooks
            version: ${{ needs.client.outputs.version }}
            isStable: ${{ needs.client.outputs.isStableRelease }}
          - name: look-and-feel react
            destination_dir: look-and-feel/react
            artifact-name: client-storybooks
            version: ${{ needs.client.outputs.version }}
            isStable: ${{ needs.client.outputs.isStableRelease }}
          - name: slash react
            destination_dir: slash/react
            artifact-name: slash-storybooks
            version: ${{ needs.slash.outputs.version }}
            isStable: ${{ needs.slash.outputs.isStableRelease }}
      max-parallel: 1

    steps:
      - name: Download storybooks
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: ${{ matrix.storybook.artifact-name }}

      - name: Upload the ${{ matrix.storybook.name }} storybook version next
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ matrix.storybook.destination_dir }}
          destination_dir: ${{ matrix.storybook.destination_dir }}/next

      - name: Upload the ${{ matrix.storybook.name }} storybook version latest
        if: matrix.storybook.isStable == 'true'
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ matrix.storybook.destination_dir }}
          destination_dir: ${{ matrix.storybook.destination_dir }}/latest

      - name: Upload the ${{ matrix.storybook.name }} storybook version ${{ matrix.storybook.version }}
        if: matrix.storybook.isStable == 'true'
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ matrix.storybook.destination_dir }}
          destination_dir: ${{ matrix.storybook.destination_dir }}/${{ matrix.storybook.version }}
