name: Publish Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    if: github.repository_owner == 'AxaFrance'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.fullSemVer }}
      isStableRelease: ${{ steps.gitversion.outputs.preReleaseTag == '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: ./.github/action/setup-node

      - name: Determine Canopee Version
        id: gitversion
        uses: ./.github/action/git-version
        with:
          configFilePath: "GitVersion.yml"

      - name: Determine Old Package Version
        id: oldpackageversion
        run: |
          SEMVER=$(echo "${{ steps.gitversion.outputs.fullSemVer }}" | grep -oE '^[0-9]+\.[0-9]+\.[0-9]+')
          SEMVER_SUFFIX=$(echo "${{ steps.gitversion.outputs.fullSemVer }}" | sed -E 's/^[0-9]+\.[0-9]+\.[0-9]+//')
          MAJOR=$(echo "$SEMVER" | cut -d. -f1)
          MINOR=$(echo "$SEMVER" | cut -d. -f2)
          PATCH=$(echo "$SEMVER" | cut -d. -f3)
          echo "FULL_SEMVER_OLD_PACKAGE=$((MAJOR + 3)).${MINOR}.${PATCH}${SEMVER_SUFFIX}" >> $GITHUB_ENV

      - name: Npm version
        run: |
          npm version "${{ steps.gitversion.outputs.fullSemVer }}" -w packages/canopee-css -w packages/canopee-react
          npm version "${{ env.FULL_SEMVER_OLD_PACKAGE }}" -w client/apollo/css -w client/apollo/react -w slash/css -w slash/react

      - name: Set to react package the @axa-fr/canopee-css dependency version
        run: |
          jq '.peerDependencies["@axa-fr/canopee-css"] = "${{ steps.gitversion.outputs.fullSemVer }}"' packages/canopee-react/package.json > temps.json && mv temps.json packages/canopee-react/package.json
          jq '.peerDependencies["@axa-fr/canopee-css"] = "${{ steps.gitversion.outputs.fullSemVer }}"' client/apollo/react/package.json > temps.json && mv temps.json client/apollo/react/package.json
          jq '.peerDependencies["@axa-fr/canopee-css"] = "${{ steps.gitversion.outputs.fullSemVer }}"' slash/react/package.json > temps.json && mv temps.json slash/react/package.json

      - name: Build packages
        run: npm run build

      - name: Config npm
        run: |
          npm config set access=public
          npm config set provenance=true

      - name: Publish latest packages
        if: steps.gitversion.outputs.preReleaseTag == ''
        run: npm publish -w packages/canopee-css -w packages/canopee-react -w client/apollo/css -w client/apollo/react -w slash/css -w slash/react --tag latest;

      - name: Publish rc packages
        if: contains(steps.gitversion.outputs.fullSemVer, 'RC')
        run: npm publish -w packages/canopee-css -w packages/canopee-react -w client/apollo/css -w client/apollo/react -w slash/css -w slash/react --tag rc;

      - name: Publish next packages
        if: steps.gitversion.outputs.preReleaseTag != '' && !contains(steps.gitversion.outputs.fullSemVer, 'RC')
        run: npm publish -w packages/canopee-css -w packages/canopee-react -w client/apollo/css -w client/apollo/react -w slash/css -w slash/react --tag next;

      - name: Create artifact folders
        uses: ./.github/action/create-storybook-artifact
        with:
          artifact-name: storybooks
          folders: "apollo/react,look-and-feel/react,slash/react"

  deploy-storybooks:
    needs:
      - publish
    runs-on: ubuntu-latest
    name: Deploy new version of storybook to gh-pages
    strategy:
      matrix:
        storybook:
          - name: slash react
            publish_dir: slash/react
            destination_dir: distributeur/react
          - name: apollo react
            publish_dir: apollo/react
            destination_dir: prospect/react
          - name: look-and-feel react
            publish_dir: look-and-feel/react
            destination_dir: client/react
      max-parallel: 1

    steps:
      - name: Download storybooks
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: storybooks

      - name: Upload the ${{ matrix.storybook.name }} storybook version next
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ matrix.storybook.publish_dir }}
          destination_dir: ${{ matrix.storybook.destination_dir }}/next

      - name: Upload the ${{ matrix.storybook.name }} storybook version latest
        if: needs.publish.outputs.isStableRelease == 'true'
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ matrix.storybook.publish_dir }}
          destination_dir: ${{ matrix.storybook.destination_dir }}/latest

      - name: Upload the ${{ matrix.storybook.name }} storybook version ${{ needs.publish.outputs.version }}
        if: needs.publish.outputs.isStableRelease == 'true'
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ matrix.storybook.publish_dir }}
          destination_dir: ${{ matrix.storybook.destination_dir }}/${{ needs.publish.outputs.version }}
